name: Hugo site CI

on:
  push:
    branches: [ master ]
    tags: '*'
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    if: "github.repository == 'grzanka/nz62www' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Hugo setup
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
      uses: peaceiris/actions-hugo@v2.5.0
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        # hugo-version: # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: false
    
    - name: Build for GH Pages
      run: hugo -b "https://grzanka.github.io/nz62www" -d docs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        
    - name: Build for IFJ server
      run: hugo 

    - name: Package release
      run: tar -zcf page.tar.gz public/*
      
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
      uses: ncipollo/release-action@v1.11.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates:  true
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifact: 'page.tar.gz'
        # The Github token.
        token:  ${{ secrets.GITHUB_TOKEN }}


